let issues = {}

issues.get_query = 
`SELECT 
'issues' AS TABLE_NAME,
T1.UUID,
T1.NUM,
T1.TYPE_UUID,
T11.NAME AS TYPE_NAME,
T1.CREATED_AT,
T1.UPDATED_AT,
T1.DELETED_AT,
T1.PROJECT_UUID,
T12.NAME AS PROJECT_NAME,
T12.SHORT_NAME AS PROJECT_SHORT_NAME,
JSONB_AGG(T13) AS VALUES
FROM 
ISSUES T1
JOIN
ISSUE_TYPES T11
ON 
T1.TYPE_UUID = T11.UUID
JOIN
PROJECTS T12
ON 
T1.PROJECT_UUID = T12.UUID
JOIN
(SELECT FV.ISSUE_UUID, FV.VALUE, F.NAME
 FROM FIELD_VALUES FV
 JOIN FIELDS F
 ON FV.FIELD_UUID = F.UUID
)T13
ON 
T1.UUID = T13.ISSUE_UUID
WHERE T1.DELETED_AT IS NULL
GROUP BY
T1.UUID,
T1.NUM,
T1.TYPE_UUID,
TYPE_NAME,
T1.CREATED_AT,
T1.UPDATED_AT,
T1.DELETED_AT,
T1.PROJECT_UUID,
PROJECT_NAME,
PROJECT_SHORT_NAME
`



module.exports = issues