name: Update Meta Version

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'meta.json' # Don't run this action if only meta.json is changed

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: dev

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Update meta.json version
      run: |
        echo "Updating meta.json version..."
        
        # Read and update version
        const fs = require('fs');
        const data = JSON.parse(fs.readFileSync('meta.json', 'utf8'));
        const [major, minor, patch] = data.version.split('.').map(Number);
        const newVersion = `${major}.${minor + 1}.${patch}`;
        data.version = newVersion;
        fs.writeFileSync('meta.json', JSON.stringify(data, null, 2));
        
        # Commit and push
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add meta.json
        git commit -m "Automatically update meta.json version to $newVersion"
        git push
