name: Update Meta Version

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'meta.json' # Don't run this action if only meta.json is changed

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: dev
        token: ${{ secrets.AUTOVERSION_TOKEN }}  # Explicitly set the token

    - name: Update meta.json version
      run: |
        echo "Updating meta.json version..."
        
        # Read and update version
        VERSION=$(jq -r '.version' meta.json)
        NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$3++; print}')
        jq ".version=\"$NEW_VERSION\"" meta.json > tmp.json && mv tmp.json meta.json

        # Rename SQL migration files
        cd server/eos/migrations
        for file in m*.sql; do
          NEW_FILE_NAME="${NEW_VERSION}_${file:1}"
          mv "$file" "$NEW_FILE_NAME"
        done
        cd -

        # Commit and push
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add meta.json server/eos/migrations/*.sql
        git commit -m "Automatically update meta.json version to $NEW_VERSION and rename SQL files"
        git push origin dev  # Push to the dev branch
